export type GlossaryCategory = "OCDS model" | "Lifecycle" | "Organizations" | "Data and mapping" | "Analysis" | "Philippine context";

export interface GlossaryEntry { term: string; slug: string; category: GlossaryCategory; definition: string; related?: string[] }

export const GLOSSARY: GlossaryEntry[] = [
  { term: "Amendment", slug: "amendment", category: "Lifecycle", definition: "A formal change to a tender, award, or contract. OCDS can describe its date, rationale, and related releases." },
  { term: "APP", slug: "app", category: "Philippine context", definition: "Annual Procurement Plan. An APP entry can provide planning context, but its identifier is not automatically the boundary of one contracting process." },
  { term: "Array", slug: "array", category: "Data and mapping", definition: "An ordered list of values or objects in JSON, such as awards[], contracts[], parties[], or tender.items[]." },
  { term: "Award", slug: "award", category: "Lifecycle", definition: "The decision to select one or more suppliers. A single contracting process can contain multiple awards." },
  { term: "Award ID", slug: "award-id", category: "OCDS model", definition: "The local identifier of an award within a contracting process, published as awards[].id." },
  { term: "Bid", slug: "bid", category: "Lifecycle", definition: "A submission by a tenderer in response to a procurement opportunity." },
  { term: "Buyer", slug: "buyer", category: "Organizations", definition: "The organization whose budget is used to purchase goods, works, or services." },
  { term: "Canonical field", slug: "canonical-field", category: "Data and mapping", definition: "A normalized internal field used between source extraction and OCDS serialization." },
  { term: "Codelist", slug: "codelist", category: "Data and mapping", definition: "A controlled set of codes used by an OCDS field to make values interoperable." },
  { term: "Closed codelist", slug: "closed-codelist", category: "Data and mapping", definition: "A codelist that only permits codes defined by the standard." },
  { term: "Compiled release", slug: "compiled-release", category: "OCDS model", definition: "A current-state view produced by merging the releases in a record according to OCDS merge rules." },
  { term: "Competition indicator", slug: "competition-indicator", category: "Analysis", definition: "A measure that raises questions about participation or competitive conditions, such as a single submitted bid." },
  { term: "Contract", slug: "contract", category: "Lifecycle", definition: "The agreement entered into following an award. Contracts reference their source award using awardID." },
  { term: "Contracting process", slug: "contracting-process", category: "OCDS model", definition: "The complete procurement lifecycle represented by one OCID, from planning or tender through award, contract, and implementation." },
  { term: "Current-state release", slug: "current-state-release", category: "Data and mapping", definition: "In this POC, one release reconstructed from flattened rows describing the presently visible lifecycle state; it is not an observed publication history." },
  { term: "Data coverage", slug: "data-coverage", category: "Analysis", definition: "The extent to which fields or lifecycle stages needed for an analysis are published." },
  { term: "Document", slug: "document", category: "Lifecycle", definition: "A notice, specification, contract, report, or other file linked from a lifecycle section." },
  { term: "ETL", slug: "etl", category: "Data and mapping", definition: "Extract, transform, load: the pipeline that reads source data, interprets and restructures it, and writes an output dataset." },
  { term: "Event", slug: "event", category: "Lifecycle", definition: "Something that happens during procurement, such as publishing a notice, making an award, signing a contract, or recording delivery." },
  { term: "Extension", slug: "extension", category: "Data and mapping", definition: "A documented addition to the core OCDS schema for concepts not covered by the base standard." },
  { term: "Field", slug: "field", category: "Data and mapping", definition: "A named data property, such as tender.title or awards[].date." },
  { term: "Flattened data", slug: "flattened-data", category: "Data and mapping", definition: "Tabular data that repeats process-level facts across rows to include items, awards, contracts, or other one-to-many entities." },
  { term: "Identifier", slug: "identifier", category: "Data and mapping", definition: "A value used to distinguish and cross-reference a process, organization, award, contract, item, or other entity." },
  { term: "Implementation", slug: "implementation", category: "Lifecycle", definition: "Information about performance after contract signature, including milestones, transactions, and documents." },
  { term: "Indicator", slug: "indicator", category: "Analysis", definition: "A calculation over structured data that summarizes behavior, quality, or a condition worth reviewing." },
  { term: "Initiation type", slug: "initiation-type", category: "OCDS model", definition: "The top-level initiationType value identifying the process as tender-initiated in OCDS 1.1." },
  { term: "Item", slug: "item", category: "Lifecycle", definition: "A good, work, or service being procured, usually published in tender.items[] and optionally repeated in awards or contracts." },
  { term: "JSON", slug: "json", category: "Data and mapping", definition: "The structured text format used to publish OCDS data." },
  { term: "Lifecycle", slug: "lifecycle", category: "Lifecycle", definition: "The progression from planning and tender through award, contract, and implementation." },
  { term: "Lot", slug: "lot", category: "Lifecycle", definition: "A division of a tender that can be bid on and awarded separately, represented using the OCDS Lots extension." },
  { term: "Mapping", slug: "mapping", category: "Data and mapping", definition: "A tested rule that translates source meaning into OCDS structure; it can involve validation, grouping, or transformation rather than simple renaming." },
  { term: "Milestone", slug: "milestone", category: "Lifecycle", definition: "A planned or completed event associated with tendering, contract preparation, or implementation." },
  { term: "Object", slug: "object", category: "Data and mapping", definition: "A JSON structure containing named fields, such as a tender, award, contract, organization, or monetary value." },
  { term: "OC4IDS", slug: "oc4ids", category: "Philippine context", definition: "The Open Contracting for Infrastructure Data Standard, designed for project-centered infrastructure disclosure across related contracting processes." },
  { term: "OCID", slug: "ocid", category: "OCDS model", definition: "The globally unique Open Contracting Identifier that joins all releases belonging to one contracting process." },
  { term: "OCDS", slug: "ocds", category: "OCDS model", definition: "The Open Contracting Data Standard: a common data model for publishing information and documents across the contracting lifecycle." },
  { term: "Open codelist", slug: "open-codelist", category: "Data and mapping", definition: "A codelist that permits additional publisher-defined codes beyond those maintained by the standard." },
  { term: "Package", slug: "package", category: "OCDS model", definition: "A publication envelope containing releases or records plus publisher, version, date, and URI metadata." },
  { term: "Party", slug: "party", category: "Organizations", definition: "An organization or person involved in a contracting process, identified once in parties[] and referenced elsewhere." },
  { term: "Path", slug: "path", category: "Data and mapping", definition: "A notation describing where a value lives in OCDS, such as contracts[].awardID." },
  { term: "Planning", slug: "planning", category: "Lifecycle", definition: "Early information about rationale, budget, project, or procurement planning before tendering." },
  { term: "Portfolio", slug: "portfolio", category: "Analysis", definition: "A non-standard analytical view summarizing multiple contracting processes in an OCDS publication." },
  { term: "Procuring entity", slug: "procuring-entity", category: "Organizations", definition: "The organization managing the procurement. It can differ from the buyer whose budget funds it." },
  { term: "Provenance", slug: "provenance", category: "Data and mapping", definition: "Information identifying where data came from, how it was transformed, and which assumptions were applied." },
  { term: "Publication gap", slug: "publication-gap", category: "Analysis", definition: "Expected information that is absent from the published data, such as an award with no visible contract." },
  { term: "Record", slug: "record", category: "OCDS model", definition: "The OCDS view of one contracting process that indexes its releases and can include compiled and versioned releases." },
  { term: "Record package", slug: "record-package", category: "OCDS model", definition: "A package containing records for one or more contracting processes." },
  { term: "Red flag", slug: "red-flag", category: "Analysis", definition: "A signal that identifies a question for review. It is not proof of wrongdoing." },
  { term: "Release", slug: "release", category: "OCDS model", definition: "An immutable publication describing information known about one contracting process at a point in time." },
  { term: "Release package", slug: "release-package", category: "OCDS model", definition: "A standard package containing one or more OCDS releases and required publication metadata." },
  { term: "Schema", slug: "schema", category: "Data and mapping", definition: "A machine-readable definition of allowed fields, structures, types, and validation constraints." },
  { term: "Source row", slug: "source-row", category: "Data and mapping", definition: "One row from an input export. Its grain must be interpreted before it becomes an OCDS entity or release." },
  { term: "Supplier", slug: "supplier", category: "Organizations", definition: "An organization selected through an award to provide goods, works, or services." },
  { term: "Tag", slug: "tag", category: "OCDS model", definition: "A release code indicating which lifecycle information the release concerns, such as tender, award, contract, or implementation." },
  { term: "Tender", slug: "tender", category: "Lifecycle", definition: "Information about the procurement opportunity, including title, method, value, period, items, and status." },
  { term: "Tenderer", slug: "tenderer", category: "Organizations", definition: "An organization that expresses interest or submits a bid." },
  { term: "Validation", slug: "validation", category: "Data and mapping", definition: "Checking data against schema rules and semantic expectations. Schema validity alone does not prove correct grouping." },
  { term: "Versioned release", slug: "versioned-release", category: "OCDS model", definition: "An optional record view that retains the history and source-release provenance of field values." }
];

export const GLOSSARY_CATEGORIES: GlossaryCategory[] = ["OCDS model", "Lifecycle", "Organizations", "Data and mapping", "Analysis", "Philippine context"];
